# Example process setting file for video2geoframes.py
# See documentation for more information
#
# Last edition : 2024-07-01

# Mandatory section
[paths]
video_file = "one/video/file.mp4"
gps_track_file = "one/track_gps/file.gpx"
output_folder = "one/folder"

# Mandatory section
[video]
# For timelapse video, set video.timelapse = [true, x] (x = framerate)
# Otherwise, set video.timelapse = [false, 0]
timelapse = [false, 0]
start_datetime = 2024-06-30T23:32:00.000
rec_timezone = "+02:00"

[process_settings]
# Mandatory setting, but ignored if video.timelapse = [true, x]
frame_sampling = 1

# Optional settings, ignored if set to 0
frame_height = 0
time_offset = +0.0

# Mandatory section
[metadata]
author = "Name or alias"
camera_maker = "One"
camera_model = "Super Cam"
